# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: csv_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'csv_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63sv_processor.proto\x12\rcsv_processor\"!\n\x11ProcessCsvRequest\x12\x0c\n\x04line\x18\x01 \x01(\t\"%\n\x12ProcessCsvResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"-\n\x1aGetProcessingResultRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"G\n\x1bGetProcessingResultResponse\x12\x15\n\rprocessed_csv\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x32\xd1\x01\n\x0c\x43svProcessor\x12S\n\nProcessCsv\x12 .csv_processor.ProcessCsvRequest\x1a!.csv_processor.ProcessCsvResponse(\x01\x12l\n\x13GetProcessingResult\x12).csv_processor.GetProcessingResultRequest\x1a*.csv_processor.GetProcessingResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csv_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSCSVREQUEST']._serialized_start=38
  _globals['_PROCESSCSVREQUEST']._serialized_end=71
  _globals['_PROCESSCSVRESPONSE']._serialized_start=73
  _globals['_PROCESSCSVRESPONSE']._serialized_end=110
  _globals['_GETPROCESSINGRESULTREQUEST']._serialized_start=112
  _globals['_GETPROCESSINGRESULTREQUEST']._serialized_end=157
  _globals['_GETPROCESSINGRESULTRESPONSE']._serialized_start=159
  _globals['_GETPROCESSINGRESULTRESPONSE']._serialized_end=230
  _globals['_CSVPROCESSOR']._serialized_start=233
  _globals['_CSVPROCESSOR']._serialized_end=442
# @@protoc_insertion_point(module_scope)
